// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi0AnKF8ybEV0_Yb7R1uieD9zpXbECYnE',
    appId: '1:1097149672224:web:54e2914d1c00f50fdd8545',
    messagingSenderId: '1097149672224',
    projectId: 'social-media-login-27446',
    authDomain: 'social-media-login-27446.firebaseapp.com',
    storageBucket: 'social-media-login-27446.appspot.com',
    measurementId: 'G-SW5MEXH3S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLuKtGxDa54dD6t4SgH5iGXEwmQWi_NGk',
    appId: '1:1097149672224:android:89f0b7cc8baf0346dd8545',
    messagingSenderId: '1097149672224',
    projectId: 'social-media-login-27446',
    storageBucket: 'social-media-login-27446.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBteuQ_iAkfk9TajLKyNuUxF0sgUcijFB8',
    appId: '1:1097149672224:ios:8bc49e98811a5f06dd8545',
    messagingSenderId: '1097149672224',
    projectId: 'social-media-login-27446',
    storageBucket: 'social-media-login-27446.appspot.com',
    androidClientId: '1097149672224-uil1o274iiqfoutt9f0h65spoak21nok.apps.googleusercontent.com',
    iosClientId: '1097149672224-v8851vk92jvlfdf2ug28f2cblhoqupja.apps.googleusercontent.com',
    iosBundleId: 'com.rani.authTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBteuQ_iAkfk9TajLKyNuUxF0sgUcijFB8',
    appId: '1:1097149672224:ios:8e65fed0100def4ddd8545',
    messagingSenderId: '1097149672224',
    projectId: 'social-media-login-27446',
    storageBucket: 'social-media-login-27446.appspot.com',
    androidClientId: '1097149672224-uil1o274iiqfoutt9f0h65spoak21nok.apps.googleusercontent.com',
    iosClientId: '1097149672224-halub064e790v08qcmkbrm3qtjsk53ja.apps.googleusercontent.com',
    iosBundleId: 'com.rani.authTestApp.RunnerTests',
  );
}
